# Generated by Django 4.2.18 on 2025-03-05 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_video_alter_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='video',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='max_grade',
            field=models.CharField(choices=[('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], default='10', max_length=2),
        ),
        migrations.AddField(
            model_name='video',
            name='min_grade',
            field=models.CharField(choices=[('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], default='6', max_length=2),
        ),
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default=None),
        ),
    ]
