# Generated by Django 4.2.18 on 2025-03-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/NybHckSEQBI', null=True),
        ),
    ]
