# Generated by Django 4.2.18 on 2025-03-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/embed/NybHckSEQBI'),
        ),
    ]
